name: WordPress Deploy

on:
  push:
    branches:
      - dev

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Validate
        run: terraform validate

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            # Sync files to EC2
            rsync -av --exclude 'wp-config.php' --exclude 'wp-content/uploads/' ./ /var/www/html/

            # Fix ownership for Apache
            sudo chown -R www-data:www-data /var/www/html

            # Fix directory and file permissions
            sudo find /var/www/html -type d -exec chmod 755 {} \;
            sudo find /var/www/html -type f -exec chmod 644 {} \;

            # Ensure Apache rewrite module is enabled
            sudo a2enmod rewrite || true

            # Reload Apache to apply changes
            sudo systemctl reload apache2
